# Generated by Django 5.2.4 on 2025-08-04 12:11

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('inventory', 'UserProfile')
    
    # Create UserProfile for all existing users
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={
                'email_verified': True,  # Mark existing users as verified
                'email_verification_token': UserProfile._meta.get_field('email_verification_token').default(),
                'email_verification_sent_at': None,
            }
        )

def reverse_create_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('inventory', 'UserProfile')
    UserProfile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
